# Generated by Django 4.2.17 on 2025-06-26 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdTrainingVersions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_name", models.CharField(max_length=255)),
                ("version_module", models.CharField(max_length=255)),
                ("version_segments", models.JSONField(blank=True, null=True)),
                ("version_labels", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="KnownAdLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label_name", models.CharField(max_length=255, unique=True)),
                (
                    "user_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="ad_media/")),
                (
                    "media_type",
                    models.CharField(
                        choices=[("audio", "Audio"), ("video", "Video")], max_length=10
                    ),
                ),
                ("module_name", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_annotated", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="AdTrainingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_name", models.CharField(max_length=255)),
                ("model_name", models.CharField(max_length=255)),
                ("epoch", models.IntegerField(blank=True, null=True)),
                ("total_epochs", models.IntegerField(blank=True, null=True)),
                ("f1_score", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("training", "Training"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="training",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "release_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ad_app.adtrainingversions",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("start_time", models.FloatField()),
                ("end_time", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_edited", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("module_name", models.CharField(max_length=255)),
                ("frame", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("audiovideo", "Audio+Video"),
                        ],
                        default="audio",
                        max_length=20,
                    ),
                ),
                (
                    "media_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_segments",
                        to="ad_app.mediafile",
                    ),
                ),
            ],
            options={"ordering": ["start_time"],},
        ),
    ]
