# Generated by Django 4.2.17 on 2025-06-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fr_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafile",
            name="media_file",
            field=models.FileField(max_length=225, upload_to="fr_media/"),
        ),
        migrations.AlterField(
            model_name="processedimage",
            name="processed_image",
            field=models.ImageField(
                default="image", max_length=300, upload_to="processed_images/"
            ),
        ),
    ]
