# Generated by Django 4.2.17 on 2025-06-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sr_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiofile",
            name="file",
            field=models.FileField(max_length=225, upload_to="uploaded_audio/"),
        ),
    ]
