# Generated by Django 4.2.17 on 2025-06-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tf_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafile",
            name="media_file",
            field=models.FileField(max_length=225, upload_to="tf_media/"),
        ),
    ]
