# Generated by Django 4.2.17 on 2025-06-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("od_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="processedimage",
            name="confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="processedimage",
            name="coverage_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="processedimage",
            name="end_time",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="processedimage",
            name="start_time",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
