# Generated by Django 4.2.17 on 2025-06-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagedetail",
            name="image",
            field=models.ImageField(
                default="image", max_length=300, upload_to="logo_images/"
            ),
        ),
    ]
